---
- name: Respond to Dynatrace
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35002

  rules:
    - name: Print Payload
      condition: event.payload is defined
      action:
        debug:
          var: event.payload
          
    - name: Dynatrace Problem Alerts
      condition: event.payload.State == "OPEN"
      action:
        run_job_template:
          name: "{{ template }}"
          organization: Default
          job_args:
            extra_vars:
              _hosts: "{{ event.payload }}"
          
