---
- name: Respond to Zabbix Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 35002

  rules:
    - name: FIM Alerts - file change
      condition: event.payload.event.operation is match('write',ignorecase=true)
      action:
        run_workflow_template:
          name: "Fim Events Workflow"
          organization: Default
