---
- name: Check URL Status
  hosts: all
  sources:
     - ansible.eda.url_check:
        urls:
          - http://'{{ URL }}'
        delay: 3

  rules:
    - name: Web site is up
      condition: event.url_check.status == "up"
      action:
        run_playbook:
          name: wowza.yml

    - name: Web site is down
      condition: event.url_check.status == "down"
      action:
        run_playbook:
          name: fix_web.yml
