---
- name: Linux - Expand Filesystem when full
  hosts: '{{ EntityName }}'
  become: yes

  tasks:
  - name: Ensure lvm2 package is present
    ansible.builtin.package:
      name: lvm2
      state: present
   
  - name: Add disk to VM on VMware
    community.vmware.vmware_guest_disk:
      name: '{{ composed_var }}'
      datacenter: "{{ datacenter }}"
      folder: "{{ folder }}"
      hostname: '{{ hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      disk:
        - size_gb: '{{ disk_size }}'
          type: thin
          unit_number: 1
          controller_number: 0
          controller_type: paravirtual
          state: present

  - name: Extend the logical volume and resize its filesystem
    community.general.lvol:
      vg: "{{ vg_name }}"
      lv: "{{ lv_name }}"
      size: "{{ size_to_add }}"
      resizefs: true
      active: true
      state: present
    register: lvol_extend_result
