---
- name: Linux - Expand Filesystem when full
  hosts: '{{ EntityName }}'
  become: yes

  tasks:
  - name: Add disk to VM on VMware
    community.vmware.vmware_guest_disk:
      name: node2-rhel9
      datacenter: "{{ datacenter }}"
      folder: "{{ folder }}"
      hostname: '{{ host }}'
      disk:
        - size_gb: 10
          type: thin
          unit_number: 1
          state: present
