---
- name: Linux - Expand Filesystem when full
  hosts: '{{ EntityName }}'
  become: yes

  tasks:
  - name: Get VM id
    vmware.vmware_rest.vcenter_vm_info:
    register: search_result
      filter_names:
      - '{{ composed_var }}'
      
  - name: print
    ansible.builtin.debug:
      var: search_result
