---
- name: Linux - Expand Filesystem when full
  hosts: '{{ EntityName }}'
  become: yes

  tasks:
  - name: Add disk to VM on VMware
    community.vmware.vmware_guest_disk:
      validate_certs: False
      hostname: "{{ composed_var }}"
      datacenter: "{{ datacenter }}"
      folder: "{{ folder }}"
      disk:
        - size_gb: 10
          type: thin
          state: present
          scsi_controller: 1
          unit_number: 1     
