---
- name: Linux - Expand Filesystem when full
  hosts: '{{ EntityName }}'
  become: yes

  tasks:
  - name: Add disk to VM on VMware
    community.vmware.vmware_guest_disk:
      name: '{{ composed_var }}'
      datacenter: "{{ datacenter }}"
      folder: "{{ folder }}"
      hostname: '{{ hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      disk:
        - size_gb: 10
          type: thin
          unit_number: 1
          controller_number: 0
          controller_type: paravirtual
          state: present
