---
- name: Linux - Expand Filesystem when full
  hosts: '{{ EntityName }}'
  become: yes

  tasks:
  - name: Add disk to VM on VMware
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: node2-rhel9
      folder: "{{ folder }}
      disk:
        size_gb: 10
        type: thin
        state: present
        #datastore: "{{ datastore_name }}"
