---
- name: Create ServiceNow Incident from EDA event
  hosts: "{{ ansible_eda.event.payload.event.host_host }}
  gather_facts: no
  become: true

  tasks:      
  - name: Create a ServiceNow Incident
    servicenow.itsm.incident:
      state: new
      caller: "ansible"
      urgency: high
      impact: high
      short_description: "Monitoring has identified a problem on {{ ansible_eda.event.payload.event.host_host }}"
      description: "{{ ansible_eda.event.payload }}"
    register: new_ticket

  - name: ServiceNow Ticket Number
    ansible.builtin.debug:
      var: new_ticket.record.number
    when: new_ticket is defined
